### ISSUE TITLE
conflict with eco

### ISSUE THREAD

**Issue by Zarkness2** [adi-itgg/FJetpackReloaded#2]
when I put your plugin I get that message and as a result I deactivate the plugins that use that library could you fix it?
https://paste.helpch.at/eyulasekah.cs

**Comment by Zarkness2** [comment]
and another thing you could add a placeholder that tells you if it is activated or not on your island to put in 1 menu and people can see if you have activated or not that other users can use the jetpack on your island? or better if you can add that in the menu /is settings you get 1 item that tells you if it is activated or not, I prefer the second one because if users find it easier to activate or deactivate it.

**Comment by adi-itgg** [comment]
> when I put your plugin I get that message and as a result I deactivate the plugins that use that library could you fix it? https://paste.helpch.at/eyulasekah.cs

i see, i will investigate first

> and another thing you could add a placeholder that tells you if it is activated or not on your island to put in 1 menu and people can see if you have activated or not that other users can use the jetpack on your island? or better if you can add that in the menu /is settings you get 1 item that tells you if it is activated or not, I prefer the second one because if users find it easier to activate or deactivate it.

i will to try add this

**Comment by Zarkness2** [comment]
ok and thank you very much

**Comment by Zarkness2** [comment]
Hello, is there any news? @adi-itgg

**Comment by Zarkness2** [comment]
I got the wrong command it is not /is settings it is /is permissions where you modify the permissions for each range of the island.

**Comment by Zarkness2** [comment]
as I see that you must be having a hard time I leave here a plugin that adds new flags to the plugin so you can get some ideas, the section where I would like it to be is in the permissions section.
https://github.com/Ynfuien/SuperiorSkyblockExtraFlags

**Comment by Zarkness2** [comment]
@adi-itgg

**Comment by Zarkness2** [comment]
Hello? @adi-itgg sorry for the mentions

**Comment by Zarkness2** [comment]
Hello?

**Comment by adi-itgg** [comment]
> Hello?

Sorry, I'm working on another project. I only continue this project when I have free time. you have to request this feature in the plugin because I can't change /is. you have to ask them to add this feature using my plugin api. but the plugin api is not yet available

**Comment by Zarkness2** [comment]
> as I see that you must be having a hard time I leave here a plugin that adds new flags to the plugin so you can get some ideas, the section where I would like it to be is in the permissions section. https://github.com/Ynfuien/SuperiorSkyblockExtraFlags

I passed you a plugin that adds things like what I had told you, so you can see how you could do it and without the superiorskyblock dev adding it, then as in that plugin the only thing I would have to do is add it in the .yml of the permission's menu.

**Comment by Zarkness2** [comment]
> > Hello?
> 
> Sorry, I'm working on another project. I only continue this project when I have free time. you have to request this feature in the plugin because I can't change /is. you have to ask them to add this feature using my plugin api. but the plugin api is not yet available

And about the other, ok, no problem, good luck with that.

**Comment by Zarkness2** [comment]
and could you upload the update fixing the problem with echo? it is in the development branch.

**Comment by Zarkness2** [comment]
what I meant was to do with your plugin as they did as they did with this one https://github.com/Ynfuien/SuperiorSkyblockExtraFlags would be to add one more flag as that plugin does

**Comment by Zarkness** [comment]
@adi-itgg

**Comment by Zarkness** [comment]
@adi-itgg

**Comment by Zarkness2** [comment]
@adi-itgg ?

**Comment by Zarkness2** [comment]
@adi-itgg

**Comment by Zarkness2** [comment]
@adi-itgg

**Comment by adi-itgg** [comment]
Give me a minute, I will continue this project today

**Comment by Zarkness2** [comment]
okey

**Comment by Zarkness2** [comment]
> as I see that you must be having a hard time I leave here a plugin that adds new flags to the plugin so you can get some ideas, the section where I would like it to be is in the permissions section. https://github.com/Ynfuien/SuperiorSkyblockExtraFlags

ok @adi-itgg don't forget to pass you a plugin where you can see how to create a flag for the superiorskyblock plus the wiki to see how to create a flag.

https://wiki.bg-software.com/superiorskyblock/overview/island-flags#create-your-own-island-flag

**Comment by adi-itgg** [comment]
> > as I see that you must be having a hard time I leave here a plugin that adds new flags to the plugin so you can get some ideas, the section where I would like it to be is in the permissions section. https://github.com/Ynfuien/SuperiorSkyblockExtraFlags
> 
> ok @adi-itgg don't forget to pass you a plugin where you can see how to create a flag for the superiorskyblock plus the wiki to see how to create a flag.
> 
> https://wiki.bg-software.com/superiorskyblock/overview/island-flags#create-your-own-island-flag

okay, i will add Flag and Privilege

**Comment by Zarkness2** [comment]
okay, thank you very much

**Comment by Zarkness2** [comment]
another thing could you add the things from the development section to master to be able to download the .jar?

**Comment by adi-itgg** [comment]
I will do it after adding this feature you asked for

**Comment by Zarkness2** [comment]
ok, I thought you had already added it.

**Comment by adi-itgg** [comment]
Maybe i will remove command ss2fjr, it's ok?

**Comment by Zarkness2** [comment]
if there is the flags and privileges option, it doesn't matter if you delete it

**Comment by adi-itgg** [comment]
ok

**Comment by adi-itgg** [comment]
@Zarkness can you try? https://github.com/adi-itgg/FJetpackReloaded/actions/runs/2727488441

> ok, I thought you had already added it.

Yeah, i forgot to add upload only

**Comment by adi-itgg** [comment]
You should add this to menus/settings.yml in superiorskyblock2 for flag

```yaml
  fjetpack_reloaded:
    settings-enabled:
      type: CHAINMAIL_CHESTPLATE
      name: '&6FJetpack Reloaded'
      lore:
        - '&7Allow player to use FJetpackReloaded inside your island.'
        - '&7Currently &aENABLED&7.'
    settings-disabled:
      type: CHAINMAIL_CHESTPLATE
      name: '&6FJetpack Reloaded'
      lore:
        - '&7Allow player to use FJetpackReloaded inside your island.'
        - '&7Currently &cDISABLED&7.'
    sound:
      type: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.2
      pitch: 0.2
```


and this is for Privilege, in menus/permissions.yml

```yaml
 fjetpack_reloaded:
    display-menu: true
    permission-enabled:
      type: CHAINMAIL_CHESTPLATE
      name: '&6FJetpackReloaded'
      lore:
        - '&7Access to use FJetpackReloaded inside the island.'
        - '&7Currently &aENABLED&7.'
    permission-disabled:
      type: CHAINMAIL_CHESTPLATE
      name: '&6FJetpackReloaded'
      lore:
        - '&7Access to use FJetpackReloaded inside the island.'
        - '&7Currently &cDISABLED&7.'
    role-permission:
      type: CHAINMAIL_CHESTPLATE
      name: '&6FJetpackReloaded'
      lore:
        - '&7Access to use FJetpackReloaded inside the island.'
        - '&7Role: &e{}&7.'
        - ''
        - '{0}'
    has-access:
      sound:
        type: ENTITY_EXPERIENCE_ORB_PICKUP
        volume: 0.2
        pitch: 0.2
    no-access:
      sound:
        type: BLOCK_ANVIL_PLACE
        volume: 0.2
        pitch: 0.2
```
